front_small_table:
    /mir_manipulation/pregrasp_planner_pipeline/pregrasp_planner:
      min_azimuth: 50.0
      max_azimuth: 100.0
      min_zenith: 160.0
      max_zenith: 180.0
      min_roll: -2.0
      max_roll: 2.0
side_table:
    /mir_manipulation/pregrasp_planner_pipeline/pregrasp_planner:
      min_azimuth: -10.0
      max_azimuth: 10.0
      min_zenith: -180.0
      max_zenith: 180.0
      min_roll: -5.0
      max_roll: 5.0

